apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: vllm-monitor
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: vllm
  namespaceSelector:
    matchNames:
      - vllm
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
