#nvidia-test.yaml
apiVersion: v1
kind: Pod
metadata:
  name: nvidia-test
spec:
  tolerations:
    - key: "sku"
      operator: "Equal"
      value: "gpu"
      effect: "NoSchedule"
  nodeSelector:
    kubernetes.azure.com/accelerator: nvidia
  restartPolicy: Never
  containers:
    - name: cuda-container
      image: nvidia/cuda:12.2.0-base-ubuntu22.04
      resources:
        limits:
          nvidia.com/gpu: 1
      command: ["nvidia-smi"]
