#service.yaml
apiVersion: v1
kind: Service
metadata:
  name: vllm-service
  namespace: vllm
spec:
  type: LoadBalancer
  selector:
    app: vllm
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8000
